<a href="https://colab.research.google.com/github/Lokeshreddy26/Final-year-project-2023/blob/main/M1_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 1: Data validation and pre-processing technique

In [ ]:
import pandas as p
import numpy as n

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = p.read_excel('WSND.xlsx')

In [ ]:
data.head()

Id  Time  Is_CH  Who_CH  Dist_To_CH  ADV_S  ADV_R  JOIN_S  JOIN_R  \
0  107033   353      1  107033         0.0      1      3       0      71   
1  115021   753      1  115021         0.0      1      5       0      59   
2  117044   853      1  117044         0.0      1      4       0      54   
3  103043   153      1  103043         0.0      1      4       0      47   
4  117044   853      1  117044         0.0      1      4       0      54   

   SCH_S  SCH_R  Rank  DATA_S  DATA_R  Data_Sent_To_BS  Dist_CH_To_BS  \
0      1      0     0       0    1349                9      162.55050   
1      1      0     0       0    1298                0        0.00000   
2     54      0     0       0       0                0        0.00000   
3      1      0     0       0    1269               14      145.08942   
4     54      0     0       0       0                0        0.00000   

   Send_code  Consumed_Energy Attack_Type  
0          0          2.03296    Grayhole  
1          0          0.00721   Blackhole  
2          0          0.00723  Scheduling  
3          0          1.88023    Grayhole  
4          0          0.00723  Scheduling

In [ ]:
data.shape

(500, 19)

In [ ]:
data.isnull().sum()

Id                 0
Time               0
Is_CH              0
Who_CH             0
Dist_To_CH         0
ADV_S              0
ADV_R              0
JOIN_S             0
JOIN_R             0
SCH_S              0
SCH_R              0
Rank               0
DATA_S             0
DATA_R             0
Data_Sent_To_BS    0
Dist_CH_To_BS      0
Send_code          0
Consumed_Energy    0
Attack_Type        0
dtype: int64

# Drop the Given Dataset

In [ ]:
df = data.dropna()

In [ ]:
df.shape

(500, 19)

In [ ]:
df.isnull().sum()

Id                 0
Time               0
Is_CH              0
Who_CH             0
Dist_To_CH         0
ADV_S              0
ADV_R              0
JOIN_S             0
JOIN_R             0
SCH_S              0
SCH_R              0
Rank               0
DATA_S             0
DATA_R             0
Data_Sent_To_BS    0
Dist_CH_To_BS      0
Send_code          0
Consumed_Energy    0
Attack_Type        0
dtype: int64

In [ ]:
df.describe()

Id         Time       Is_CH         Who_CH  Dist_To_CH  \
count     500.000000   500.000000  500.000000     500.000000  500.000000   
mean   172813.128000   693.100000    0.800000  172811.928000    5.354777   
std    116323.806057   386.906168    0.400401  116324.445235   11.825196   
min    101021.000000    53.000000    0.000000  101021.000000    0.000000   
25%    110024.000000   503.000000    1.000000  110024.000000    0.000000   
50%    111060.000000   553.000000    1.000000  111093.000000    0.000000   
75%    118058.000000   903.000000    1.000000  118058.000000    0.000000   
max    402069.000000  1253.000000    1.000000  402069.000000   43.036870   

            ADV_S       ADV_R      JOIN_S      JOIN_R       SCH_S       SCH_R  \
count  500.000000  500.000000  500.000000  500.000000  500.000000  500.000000   
mean     1.800000    8.140000    0.200000   18.596000    4.840000    0.200000   
std      2.137554    8.517599    0.400401   21.122526   11.117986    0.400401   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000    2.000000    0.000000    0.000000    0.000000    0.000000   
50%      1.000000    4.000000    0.000000   14.000000    1.000000    0.000000   
75%      1.000000    9.000000    0.000000   31.000000    1.000000    0.000000   
max      6.000000   28.000000    1.000000   75.000000   54.000000    1.000000   

             Rank      DATA_S       DATA_R  Data_Sent_To_BS  Dist_CH_To_BS  \
count  500.000000  500.000000   500.000000       500.000000     500.000000   
mean     4.442000    5.780000   477.358000         5.760000      48.664143   
std     10.363853   11.755338   588.837575         7.959466      61.204942   
min      0.000000    0.000000     0.000000         0.000000       0.000000   
25%      0.000000    0.000000     0.000000         0.000000       0.000000   
50%      0.000000    0.000000     0.000000         0.000000       0.000000   
75%      0.000000    0.000000  1166.000000        13.000000     115.309420   
max     37.000000   32.000000  1350.000000        29.000000     162.550500   

        Send_code  Consumed_Energy  
count  500.000000       500.000000  
mean     0.338000         0.425383  
std      0.707642         0.718673  
min      0.000000         0.002250  
25%      0.000000         0.007230  
50%      0.000000         0.058200  
75%      0.000000         0.242550  
max      2.000000         2.069590

In [ ]:
df.columns

Index(['Id', 'Time', 'Is_CH', 'Who_CH', 'Dist_To_CH', 'ADV_S', 'ADV_R',
       'JOIN_S', 'JOIN_R', 'SCH_S', 'SCH_R', 'Rank', 'DATA_S', 'DATA_R',
       'Data_Sent_To_BS', 'Dist_CH_To_BS', 'Send_code', 'Consumed_Energy',
       'Attack_Type'],
      dtype='object')

In [ ]:
del df['Id']

In [ ]:
df.columns

Index(['Time', 'Is_CH', 'Who_CH', 'Dist_To_CH', 'ADV_S', 'ADV_R', 'JOIN_S',
       'JOIN_R', 'SCH_S', 'SCH_R', 'Rank', 'DATA_S', 'DATA_R',
       'Data_Sent_To_BS', 'Dist_CH_To_BS', 'Send_code', 'Consumed_Energy',
       'Attack_Type'],
      dtype='object')

In [ ]:
df.Rank.unique()

array([ 0, 10,  3, 33, 31, 24, 20, 37], dtype=int64)

In [ ]:
df.Who_CH.unique()

array([107033, 115021, 117044, 103043, 402054, 201061, 118058, 103003,
       111093, 402063, 110024, 101041, 117039, 117095, 103029, 118031,
       111028, 402069, 118046, 110044, 117061, 201021, 102040, 105005,
       106079, 101021], dtype=int64)

In [ ]:
df.Data_Sent_To_BS.unique()

array([ 9,  0, 14, 13, 29, 15, 23,  7], dtype=int64)

In [ ]:
df.Consumed_Energy.unique()

array([2.03296, 0.00721, 0.00723, 1.88023, 0.24255, 0.00719, 0.00724,
       2.06959, 0.04156, 0.04172, 0.23082, 2.0577 , 0.00225, 0.00722,
       0.00736, 0.057  , 0.0582 , 0.21998, 1.92349, 0.00728, 0.0072 ,
       0.05904, 0.05894, 0.92063, 1.64035, 0.1789 ])

In [ ]:
df.Attack_Type.unique()

array(['Grayhole', 'Blackhole', 'Scheduling', 'Flooding', 'Normal'],
      dtype=object)

In [ ]:
p.Categorical(df['Is_CH']).describe()

counts  freqs
categories               
0              100    0.2
1              400    0.8

In [ ]:
p.Categorical(df['DATA_S']).describe()

counts  freqs
categories               
0              400  0.800
22              31  0.062
32              69  0.138

In [ ]:
p.Categorical(df['Attack_Type']).describe()

counts  freqs
categories               
Blackhole      100    0.2
Flooding       100    0.2
Grayhole       100    0.2
Normal         100    0.2
Scheduling     100    0.2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Time             500 non-null    int64  
 1   Is_CH            500 non-null    int64  
 2   Who_CH           500 non-null    int64  
 3   Dist_To_CH       500 non-null    float64
 4   ADV_S            500 non-null    int64  
 5   ADV_R            500 non-null    int64  
 6   JOIN_S           500 non-null    int64  
 7   JOIN_R           500 non-null    int64  
 8   SCH_S            500 non-null    int64  
 9   SCH_R            500 non-null    int64  
 10  Rank             500 non-null    int64  
 11  DATA_S           500 non-null    int64  
 12  DATA_R           500 non-null    int64  
 13  Data_Sent_To_BS  500 non-null    int64  
 14  Dist_CH_To_BS    500 non-null    float64
 15  Send_code        500 non-null    int64  
 16  Consumed_Energy  500 non-null    float64
 17  Attack_Type     

In [ ]:
df.columns

Index(['Time', 'Is_CH', 'Who_CH', 'Dist_To_CH', 'ADV_S', 'ADV_R', 'JOIN_S',
       'JOIN_R', 'SCH_S', 'SCH_R', 'Rank', 'DATA_S', 'DATA_R',
       'Data_Sent_To_BS', 'Dist_CH_To_BS', 'Send_code', 'Consumed_Energy',
       'Attack_Type'],
      dtype='object')

In [ ]:
print("Minimum value of bmi Level is:", df.Dist_CH_To_BS.min())
print("Maximum value of bmi Level is:", df.Dist_CH_To_BS.max())

Minimum value of bmi Level is: 0.0
Maximum value of bmi Level is: 162.5505


In [ ]:
print("Minimum value of Consumed_Energy is:", df.Consumed_Energy.min())
print("Maximum value of Consumed_Energy is:", df.Consumed_Energy.max())

Minimum value of Consumed_Energy is: 0.00225
Maximum value of Consumed_Energy is: 2.06959


In [ ]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['Attack_Type']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [ ]:
df.head(10)

Time  Is_CH  Who_CH  Dist_To_CH  ADV_S  ADV_R  JOIN_S  JOIN_R  SCH_S  \
0   353      1  107033     0.00000      1      3       0      71      1   
1   753      1  115021     0.00000      1      5       0      59      1   
2   853      1  117044     0.00000      1      4       0      54     54   
3   153      1  103043     0.00000      1      4       0      47      1   
4   853      1  117044     0.00000      1      4       0      54     54   
5  1253      1  402054     0.00000      6     22       0       0      0   
6  1003      1  201061     0.00000      1      7       0      31      1   
7   903      1  118058     0.00000      1      5       0      27     27   
8   153      1  103003     0.00000      1      4       0      22      1   
9   553      0  111093    15.17406      0      2       1       0      0   

   SCH_R  Rank  DATA_S  DATA_R  Data_Sent_To_BS  Dist_CH_To_BS  Send_code  \
0      0     0       0    1349                9      162.55050          0   
1      0     0       0    1298                0        0.00000          0   
2      0     0       0       0                0        0.00000          0   
3      0     0       0    1269               14      145.08942          0   
4      0     0       0       0                0        0.00000          0   
5      0     0       0       0               13      142.10787          0   
6      0     0       0    1240                0        0.00000          0   
7      0     0       0       0                0        0.00000          0   
8      0     0       0    1166               29       85.19787          0   
9      1    10      22       0                0        0.00000          1   

   Consumed_Energy  Attack_Type  
0          2.03296            2  
1          0.00721            0  
2          0.00723            4  
3          1.88023            2  
4          0.00723            4  
5          0.24255            1  
6          0.00719            0  
7          0.00724            4  
8          2.06959            2  
9          0.04156            3

In [ ]:
df.Attack_Type.unique()

array([2, 0, 4, 1, 3])