<a href="https://colab.research.google.com/github/Lokeshreddy26/Final-year-project-2023/blob/main/M5_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module - 5 KNN

In [ ]:
import pandas as p
import numpy as n
import seaborn as s
import matplotlib.pyplot as plt

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data=p.read_excel('WSND.xlsx')

In [ ]:
df=data.dropna()

In [ ]:
df.columns

Index(['Id', 'Time', 'Is_CH', 'Who_CH', 'Dist_To_CH', 'ADV_S', 'ADV_R',
       'JOIN_S', 'JOIN_R', 'SCH_S', 'SCH_R', 'Rank', 'DATA_S', 'DATA_R',
       'Data_Sent_To_BS', 'Dist_CH_To_BS', 'Send_code', 'Consumed_Energy',
       'Attack_Type'],
      dtype='object')

In [ ]:
del df['Id']
del df['Time']
del df['Is_CH']
del df['JOIN_R']
del df['DATA_R']

In [ ]:
df.columns

Index(['Who_CH', 'Dist_To_CH', 'ADV_S', 'ADV_R', 'JOIN_S', 'SCH_S', 'SCH_R',
       'Rank', 'DATA_S', 'Data_Sent_To_BS', 'Dist_CH_To_BS', 'Send_code',
       'Consumed_Energy', 'Attack_Type'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['Attack_Type']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [ ]:
#preprocessing, split test and dataset, split response variable
X = df.drop(labels='Attack_Type', axis=1)
#Response variable
y = df.loc[:,'Attack_Type']    

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1, stratify=y)
print("Number of training dataset: ", len(X_train))
print("Number of test dataset: ", len(X_test))
print("Total number of dataset: ", len(X_train)+len(X_test))


Number of training dataset:  350
Number of test dataset:  150
Total number of dataset:  500


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)
predictknn = knn.predict(X_test)

print("")
print('Classification report of KNN Results:')
print("")
print(classification_report(y_test,predictknn))

print("")
cm1=confusion_matrix(y_test,predictknn)
print('Confusion Matrix result of KNN is:\n',cm1)
print("")

accuracy = accuracy_score(y_test, predictknn)
print('Accuracy of KNN is:', accuracy*100)


Classification report of KNN Results:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00        30
           2       1.00      1.00      1.00        30
           3       1.00      1.00      1.00        30
           4       1.00      1.00      1.00        30

    accuracy                           1.00       150
   macro avg       1.00      1.00      1.00       150
weighted avg       1.00      1.00      1.00       150


Confusion Matrix result of KNN is:
 [[30  0  0  0  0]
 [ 0 30  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 30]]

Accuracy of KNN is: 100.0
