<a href="https://colab.research.google.com/github/Lokeshreddy26/Final-year-project-2023/blob/main/M7_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 7 : Performance measurements of Logistic Regression

In [ ]:
#import library packages
import pandas as p
import matplotlib.pyplot as plt
import seaborn as s
import numpy as n

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#Load given dataset
data = p.read_excel("WSND.xlsx")

In [ ]:
df = data.dropna()

In [ ]:
df.columns

Index(['Id', 'Time', 'Is_CH', 'Who_CH', 'Dist_To_CH', 'ADV_S', 'ADV_R',
       'JOIN_S', 'JOIN_R', 'SCH_S', 'SCH_R', 'Rank', 'DATA_S', 'DATA_R',
       'Data_Sent_To_BS', 'Dist_CH_To_BS', 'Send_code', 'Consumed_Energy',
       'Attack_Type'],
      dtype='object')

In [ ]:
df['Attack_Type'].unique()

array(['Grayhole', 'Blackhole', 'Scheduling', 'Flooding', 'Normal'],
      dtype=object)

In [ ]:
df['Attack_Type'].value_counts()

Scheduling    100
Blackhole     100
Grayhole      100
Flooding      100
Normal        100
Name: Attack_Type, dtype: int64

In [ ]:
del df['Id']
del df['Time']
del df['Is_CH'] 
del df['DATA_R']
del df['JOIN_R']

In [ ]:
df.columns

Index(['Who_CH', 'Dist_To_CH', 'ADV_S', 'ADV_R', 'JOIN_S', 'SCH_S', 'SCH_R',
       'Rank', 'DATA_S', 'Data_Sent_To_BS', 'Dist_CH_To_BS', 'Send_code',
       'Consumed_Energy', 'Attack_Type'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['Attack_Type']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [ ]:
df['Attack_Type'].unique()

array([2, 0, 4, 1, 3])

In [ ]:
#preprocessing, split test and dataset, split response variable
X = df.drop(labels='Attack_Type', axis=1)
#Response variable
y = df.loc[:,'Attack_Type']  

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1, stratify=y)
print("Number of training dataset: ", len(X_train))
print("Number of test dataset: ", len(X_test))
print("Total number of dataset: ", len(X_train)+len(X_test))

Number of training dataset:  350
Number of test dataset:  150
Total number of dataset:  500


In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [ ]:
lr = LogisticRegression(max_iter=20)
lr.fit(X_train,y_train)
predictlr = lr.predict(X_test)

print("")
print('Classification report of Logistic Regression Results:')
print("")
print(classification_report(y_test,predictlr))

print("")
cm1=confusion_matrix(y_test,predictlr)
print('Confusion Matrix result of Logistic Regression is:\n',cm1)
print("")

accuracy = accuracy_score(y_test, predictlr)
print('Accuracy of Logistic Regression is:', accuracy*100)


Classification report of Logistic Regression Results:

              precision    recall  f1-score   support

           0       0.83      1.00      0.91        30
           1       0.52      1.00      0.68        30
           2       1.00      0.07      0.12        30
           3       1.00      1.00      1.00        30
           4       1.00      0.80      0.89        30

    accuracy                           0.77       150
   macro avg       0.87      0.77      0.72       150
weighted avg       0.87      0.77      0.72       150


Confusion Matrix result of Logistic Regression is:
 [[30  0  0  0  0]
 [ 0 30  0  0  0]
 [ 0 28  2  0  0]
 [ 0  0  0 30  0]
 [ 6  0  0  0 24]]

Accuracy of Logistic Regression is: 77.33333333333333
